import { Navigate, Routes, Route } from 'react-router-dom'
import BooksPage from './pages/Books/BooksPage'
import LoginPage from './features/auth/pages/LoginPage'
import ActivateAccountPage from './features/auth/pages/ActivateAccountPage'
import ForgotPasswordPage from './features/auth/pages/ForgotPasswordPage'
import UpdatePasswordPage from './features/auth/pages/UpdatePasswordPage'
import MyProfilePage from './features/auth/pages/MyProfilePage'
import ProtectedRoute from './features/auth/components/ProtectedRoute'
import UsersPage from './features/users/pages/UsersPage'
import RolesPage from './features/roles/pages/RolesPage'
import ReportsPage from './features/reports/pages/ReportsPage'
import AssetsPage from './features/registers/pages/AssetsPage'
import PumpsPage from './features/registers/pages/PumpsPage'
import PoolsPage from './features/pools/pages/PoolsPage'
import SpaPage from './features/spa/pages/SpaPage'
import LegionellaPage from './features/legionella/pages/LegionellaPage'
import ClimatizersPage from './features/climatizers/pages/ClimatizersPage'
import FancoilsPage from './features/fancoils/pages/FancoilsPage'
import ElectricalPanelsPage from './features/electricalpanels/pages/ElectricalPanelsPage'
import ElectricalPanelDetailPage from './features/electricalpanels/pages/ElectricalPanelDetailPage'
import ElectricalPanelsReportPage from './features/electricalpanels/pages/ElectricalPanelsReportPage'
import PhotoluminescentPage from './features/photoluminescent/pages/PhotoluminescentPage'
import EmergencyLightsPage from './features/emergencylights/pages/EmergencyLightsPage'
import FireDoorsPage from './features/firedoors/pages/FireDoorsPage'
import CalibrationsPage from './features/calibrations/pages/CalibrationsPage'
import FireEquipmentPage from './features/fireequipment/pages/FireEquipmentPage'
import ExtinguishersPage from './features/fireequipment/pages/ExtinguishersPage'
import BiePage from './features/fireequipment/pages/BiePage'
import SprinklersPage from './features/fireequipment/pages/SprinklersPage'
import PciReviewPage from './features/fireequipment/pages/PciReviewPage'
import ApparatusRegistryPage from './features/apparatusregistry/pages/ApparatusRegistryPage'
import ApparatusRegistryDetailPage from './features/apparatusregistry/pages/ApparatusRegistryDetailPage'
import ApparatusRegistryReportPage from './features/apparatusregistry/pages/ApparatusRegistryReportPage'
import MaintenancePage from './features/maintenance/pages/MaintenancePage'
import MaintenanceConfigurationPage from './features/maintenance/pages/MaintenanceConfigurationPage'
import MaintenancePamPage from './features/maintenance/pages/MaintenancePamPage'
import MaintenancePamDetailPage from './features/maintenance/pages/MaintenancePamDetailPage'
import MaintenanceRecordsPage from './features/maintenance/pages/MaintenanceRecordsPage'
import MaintenanceRecordPage from './features/maintenance/pages/MaintenanceRecordPage'
import MaintenanceOperationHomePage from './features/maintenance/pages/MaintenanceOperationHomePage'
import MaintenanceAuditPage from './features/maintenance/pages/MaintenanceAuditPage'
import MaintenanceLandingPage from './features/maintenance/pages/MaintenanceLandingPage'
import ProvidersPage from './features/providers/pages/ProvidersPage'
import ActionsPage from './features/actions/pages/ActionsPage'

export default function App() {
return (<Routes><Route path="/login" element={<LoginPage />} /><Route path="/activate" element={<ActivateAccountPage />} /><Route path="/forgot-password" element={<ForgotPasswordPage />} /><Route path="/update-password" element={<UpdatePasswordPage />} /><Route element={<ProtectedRoute />}><Route path="/" element={<BooksPage />} /><Route path="/users" element={<UsersPage />} /><Route path="/roles" element={<RolesPage />} /><Route path="/profile" element={<MyProfilePage />} /><Route path="/reports" element={<ReportsPage />} /><Route path="/pam" element={<MaintenancePamPage />} /><Route path="/planning" element={<Navigate to="/maintenance/pam" replace />} /><Route path="/providers" element={<ProvidersPage />} /><Route path="/actions" element={<ActionsPage />} /><Route path="/assets" element={<AssetsPage />} /><Route path="/pumps" element={<PumpsPage />} /><Route path="/pools" element={<PoolsPage />} /><Route path="/spa" element={<SpaPage />} /><Route path="/legionella" element={<LegionellaPage />} /><Route path="/climatizers" element={<ClimatizersPage />} /><Route path="/fancoils" element={<FancoilsPage />} /><Route path="/electricalpanels" element={<ElectricalPanelsPage />} /><Route path="/electricalpanels/new" element={<ElectricalPanelDetailPage />} /><Route path="/electricalpanels/report" element={<ElectricalPanelsReportPage />} /><Route path="/electricalpanels/:id" element={<ElectricalPanelDetailPage />} /><Route path="/apparatusregistry" element={<ApparatusRegistryPage />} /><Route path="/maintenance" element={<MaintenanceLandingPage />} /><Route path="/maintenance/pam" element={<MaintenancePamPage />} /><Route path="/maintenance/pam/:apparatusId" element={<MaintenancePamDetailPage />} /><Route path="/maintenance/records" element={<MaintenanceRecordsPage />} /><Route path="/maintenance/record" element={<MaintenanceRecordPage />} /><Route path="/maintenance/operation" element={<MaintenanceOperationHomePage />} /><Route path="/maintenance/plans" element={<MaintenancePage />} /><Route path="/maintenance/configuration" element={<MaintenanceConfigurationPage />} /><Route path="/maintenance/audit" element={<MaintenanceAuditPage />} /><Route path="/apparatusregistry/new" element={<ApparatusRegistryDetailPage />} /><Route path="/apparatusregistry/report" element={<ApparatusRegistryReportPage />} /><Route path="/apparatusregistry/:id" element={<ApparatusRegistryDetailPage />} /><Route path="/photoluminescent" element={<PhotoluminescentPage />} /><Route path="/emergencylights" element={<EmergencyLightsPage />} /><Route path="/firedoors" element={<FireDoorsPage />} /><Route path="/calibrations" element={<CalibrationsPage />} /><Route path="/fireequipment" element={<FireEquipmentPage />} /><Route path="/fireequipment/extinguishers" element={<ExtinguishersPage />} /><Route path="/fireequipment/bie" element={<BiePage />} /><Route path="/fireequipment/sprinklers" element={<SprinklersPage />} /><Route path="/fireequipment/pci-review" element={<PciReviewPage />} /></Route></Routes>)
}