-- Arias PAM — carga inicial de Cuadros Eléctricos BT
-- Fuente: R-SSTT-01-08 CUADROS BT v0(9).xlsx / hoja SSTT BT
-- Se cargan las posiciones 1-40. Las posiciones 41-60 del Excel están vacías y no se crean.
-- La posición 7 se conserva porque existe en el Excel, aunque CUADRO está vacío.
-- Las fechas de instalación/revisión no se inventan: el Excel no las contiene.
-- Los checks se cargan pendientes porque las 10 celdas de comprobación del Excel están vacías.
-- El estado OPERATIVE es un valor inicial de Arias PAM; NO procede del Excel.

begin;

alter table public.electrical_panels
  add column if not exists excel_id integer;

alter table public.electrical_panels
  add column if not exists source_document text;

-- Preflight: esta consulta debe devolver 0 filas antes del índice único.
select code, count(*) as total
from public.electrical_panels
group by code
having count(*) > 1
order by code;

create unique index if not exists ux_electrical_panels_code
  on public.electrical_panels (code);

create unique index if not exists ux_electrical_panels_excel_id
  on public.electrical_panels (excel_id)
  where excel_id is not null;

-- Vincular por código cualquier registro de prueba ya existente CBT-001..CBT-040.
with imported(code, excel_id) as (
  values
    ('CBT-001', 1),
    ('CBT-002', 2),
    ('CBT-003', 3),
    ('CBT-004', 4),
    ('CBT-005', 5),
    ('CBT-006', 6),
    ('CBT-007', 7),
    ('CBT-008', 8),
    ('CBT-009', 9),
    ('CBT-010', 10),
    ('CBT-011', 11),
    ('CBT-012', 12),
    ('CBT-013', 13),
    ('CBT-014', 14),
    ('CBT-015', 15),
    ('CBT-016', 16),
    ('CBT-017', 17),
    ('CBT-018', 18),
    ('CBT-019', 19),
    ('CBT-020', 20),
    ('CBT-021', 21),
    ('CBT-022', 22),
    ('CBT-023', 23),
    ('CBT-024', 24),
    ('CBT-025', 25),
    ('CBT-026', 26),
    ('CBT-027', 27),
    ('CBT-028', 28),
    ('CBT-029', 29),
    ('CBT-030', 30),
    ('CBT-031', 31),
    ('CBT-032', 32),
    ('CBT-033', 33),
    ('CBT-034', 34),
    ('CBT-035', 35),
    ('CBT-036', 36),
    ('CBT-037', 37),
    ('CBT-038', 38),
    ('CBT-039', 39),
    ('CBT-040', 40)
)
update public.electrical_panels p
set excel_id = i.excel_id,
    source_document = 'R-SSTT-01-08 CUADROS BT v0(9).xlsx'
from imported i
where p.code = i.code
  and p.excel_id is null;

insert into public.electrical_panels (
  excel_id, code, name, location, manufacturer, model,
  installation_date, inspection_date, technician, status,
  observations, reviews, source_document, updated_at
)
values
(1, 'CBT-001', 'SBH-SUMINISTRO EMERGE0', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(2, 'CBT-002', 'SBH-CONMUTACION', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(3, 'CBT-003', 'SBH-IGA1', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(4, 'CBT-004', 'SBH-QGD2', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(5, 'CBT-005', 'SBH-SUMINIST. EMERGENCIA1', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(6, 'CBT-006', 'SBH-SUMINIST. EMERGENCIA2', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(7, 'CBT-007', null, 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(8, 'CBT-008', 'SBH-SUMINISTRO NORMAL0', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(9, 'CBT-009', 'SBH-CABLEADO', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(10, 'CBT-010', 'SBH-SUMINISTRO NORMAL1', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(11, 'CBT-011', 'SBH-BYPASS', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(12, 'CBT-012', 'SBH-IGA2', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(13, 'CBT-013', 'SBH-PARKING', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(14, 'CBT-014', 'SBH-QGBD', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(15, 'CBT-015', 'SBH-SUBESC 0', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(16, 'CBT-016', 'SBH-SUBESC 1', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(17, 'CBT-017', 'SBH-SUB SERV. GENERALES', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(18, 'CBT-018', 'SBH-SAI', 'C.G.B.T.', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(19, 'CBT-019', 'SBH-SALA BOMBAS', 'SSTT AGUA-1', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(20, 'CBT-020', 'SBH-CONTROL BOMBAS', 'SSTT AGUA-1', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(21, 'CBT-021', 'SBH-GYM SPA', 'GYM', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(22, 'CBT-022', 'SBH-SSTT SPA', 'SPA', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(23, 'CBT-023', 'SBH-GRUPO', 'PLANTA-2', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(24, 'CBT-024', 'SBH-PB', 'SSTT BACK P0', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(25, 'CBT-025', 'SBH-TERRAZA', 'OFFICE COCTAIL P0', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(26, 'CBT-026', 'SBH-COCINA', 'D. CHEF', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(27, 'CBT-027', 'SBH-ECHO', 'ECHO', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(28, 'CBT-028', 'SBH-P1', 'P1', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(29, 'CBT-029', 'SBH-DJ', 'CABINA DJ', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(30, 'CBT-030', 'SHB-P2 P3', 'PLANTA 2', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(31, 'CBT-031', 'SBH-P4 P5', 'PLANTA 4', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(32, 'CBT-032', 'SBH-P6 P7', 'PLANTA 6', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(33, 'CBT-033', 'SBH-P8 P9', 'PLANTA 8', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(34, 'CBT-034', 'SBH-P10 P11', 'PLANTA 10', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(35, 'CBT-035', 'SBH-P12 P13', 'PLANTA 12', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(36, 'CBT-036', 'SBH-P14', 'PLANTA 14', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(37, 'CBT-037', 'SBH-P15', 'PLANTA 15', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(38, 'CBT-038', 'SBH-P16', 'PLANTA 16', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(39, 'CBT-039', 'SBH-P17', 'PLANTA 17', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now()),
(40, 'CBT-040', 'SBH-P18', 'PLANTA 18', null, null, null, null, null, 'OPERATIVE', null, '[{"id": "terminal-tightening", "name": "Apriete de tornillos y bornes", "sourceName": "Comprobar aprietes de tornillos y bornes", "checked": false}, {"id": "interior-cleaning", "name": "Limpieza general", "sourceName": "Limpieza general con aire a presión", "checked": false}, {"id": "wiring", "name": "Cables interiores", "sourceName": "Inspeccionar cables interiores", "checked": false}, {"id": "differentials", "name": "Mecanismos diferenciales", "sourceName": "Accionar pulsador de mecanismos diferenciales", "checked": false}, {"id": "contactors", "name": "Contactores", "sourceName": "Comprobar accionamiento mecánico de contactores maniobras", "checked": false}, {"id": "grounding", "name": "Puesta a tierra", "sourceName": "Verificar puesta a tierra del cuadro, medir resistencia de tierra (Meger)", "checked": false}, {"id": "insulation", "name": "Aislamiento y diferencial", "sourceName": "Verificar aislamiento de cada salida y actuación del diferencial (Meger)", "checked": false}, {"id": "schematics", "name": "Esquemas eléctricos", "sourceName": "Verificar existencia de esquemas eléctricos", "checked": false}, {"id": "selectivity", "name": "Selectividad de circuitos", "sourceName": "Verificar selectividad de circuitos", "checked": false}, {"id": "general", "name": "Estado general del cuadro", "sourceName": "Estado general del cuadro (chasis)", "checked": false}]'::jsonb, 'R-SSTT-01-08 CUADROS BT v0(9).xlsx', now())
on conflict (excel_id) where excel_id is not null do update set
  code = excluded.code,
  name = excluded.name,
  location = excluded.location,
  source_document = excluded.source_document,
  updated_at = now();

commit;

select excel_id, code, name, location
from public.electrical_panels
where excel_id between 1 and 40
order by excel_id;
